---
version: "3.8"
services:
  movies:
    image: veeranekkanti/appmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: veeranekkanti/apptrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: veeranekkanti/apprecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    images: veeranekkanti/appdth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
